### PR TITLE
packer: add vars + readme for building headless/remote

### PR DESCRIPTION
**Pull request by damonbreeden**

### CODE REVIEW

**Comment by trodemaster** [comment]
This is interesting. The defaults will need to match existing default values that packer has currently. For example, the defaults in the PR for vnc port locks the VNC port range down. This breaks the ability to build multiple images at the same time. Please update the PR  with variable defaults that match values used before this PR. Once that's done I'll have a look and see if this can be merged.

**Comment by damonbreeden** [comment]
that's legitimate, i'll make those changes

**Comment by damonbreeden** [comment]
i amended the commit & force pushed the update with the defaults from https://www.packer.io/docs/builders/vmware/iso#run-configuration

**Comment by trodemaster** [comment]
Variables defaults look good. I'm hesitant to add the readme info as I'm not clear from the description how this works. If your running packer locally how does it start the hypervisor on the remote system? The ssh and vnc config is understandable to connect to the remote guest.

**Comment by damonbreeden** [comment]
> If your running packer locally how does it start the hypervisor on the remote system

everything (code, packer, fusion) runs on the remote machine
The only thing that runs locally is ssh (and vs code for example)

**Comment by trodemaster** [comment]
Ah Ok I have done that before. Let's leave that out of the readme as it will likely be confusing for most users.

**Pull request merged**
